title: Your Site Name
description: Your site description

# Site settings
url: https://yourdomain.com
baseurl: ""

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - src
  - dist
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Collections (for Obsidian notes)
collections:
  notes:
    output: true
    permalink: /notes/:slug/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"

# Plugins
plugins:
  - jekyll-last-modified-at
